# Generated by Django 4.1.3 on 2023-03-09 03:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishMain', '0003_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_viewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnglishMain.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnglishMain.user_details')),
            ],
        ),
    ]
