# Generated by Django 3.2.17 on 2023-03-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishMain', '0004_course_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='usertype',
            field=models.CharField(default='User', max_length=20),
        ),
    ]
