# Generated by Django 3.2.17 on 2023-03-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishMain', '0005_user_details_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='photo',
            field=models.ImageField(default='No Photo Available', upload_to='images'),
        ),
    ]
